auctionrush/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views
from auctions import views as auctions_views

urlpatterns = [
    path('', auctions_views.index, name="index"),
    path('about/', auctions_views.about, name="about"),
    path('myauctions/', auctions_views.my_auctions, name="my_auctions"),
    path('mybids/', auctions_views.my_bids, name="my_bids"),
    path('auctions/', include('auctions.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path("accounts/register", views.register, name="register"),
    path('admin/', admin.site.urls),
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

auctions/urls.py
from django.urls import path

from . import views
app_name = 'auctions'

urlpatterns = [
    path('create/', views.create, name='create'),
    # path('myauctions/', views.my_auctions, name='my_auctions'),
    # Example: /auctions/
    path('', views.auctions, name='auctions'),
    # Example: /auctions/5/
    path('<int:auction_id>/', views.detail, name='detail'),
    # Example: /auctions/5/results/
    # path('<int:auction_id>/results/', views.results, name='results'),
    # Example: /auctions/5/bid/
    path('<int:auction_id>/bid/', views.bid, name='bid'),
    path("search", views.search, name="search"),
    
]

auctions/models.py
from django.db import models
from django.contrib.auth.models import User
from datetime import timedelta, datetime, timezone
from math import ceil

class Auction(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=300)
    desc = models.CharField(max_length=2000, blank=True)
    image = models.ImageField(upload_to='auction_images/', blank=True, default = 'auction_images/default/default.svg')
    min_value = models.IntegerField()
    date_added = models.DateTimeField()
    duration = models.FloatField(default=24)
    is_active = models.BooleanField(default=True)
    winner = models.ForeignKey(User, on_delete=models.SET("(deleted)"),
                               blank=True,
                               null=True,
                               related_name="auction_winner",
                               related_query_name="auction_winner")
    final_value = models.IntegerField(blank=True, null=True)

    def resolve(self):
        if self.is_active:
            # If expired
            if self.has_expired():
                # Define winner
                highest_bid = Bid.objects.filter(auction=self).order_by('-amount').order_by('date').first()
                if highest_bid:
                    self.winner = highest_bid.bidder
                    self.final_value = highest_bid.amount
                self.is_active = False
                self.save()

    # Helper function that determines if the auction has expired
    def has_expired(self):
        now = datetime.now(timezone.utc)
        expiration = self.date_added + timedelta(hours=self.duration)
        if now > expiration:
            return True
        else:
            return False

    # Returns the ceiling of remaining_time in minutes
    @property
    def remaining_minutes(self):
        if self.is_active:
            now = datetime.now(timezone.utc)
            expiration = self.date_added + timedelta(hours=self.duration)
            minutes_remaining = ceil((expiration - now).total_seconds() / (60))
            ans = str(minutes_remaining // 60) + "H "+ str(minutes_remaining % 60) + "M"
            return(ans)
        else:
            return(0)

class Bid(models.Model):
    bidder = models.ForeignKey(User, on_delete=models.CASCADE)
    auction = models.ForeignKey(Auction, on_delete=models.CASCADE)
    amount = models.IntegerField()
    # is_cancelled = models.BooleanField(default=False)
    date = models.DateTimeField('when the bid was made')

auctions/forms.py
from django import forms

class ImageUploadForm(forms.Form):
    """Image upload form."""
    image = forms.ImageField()

auctions/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.template import loader
from django.contrib.auth.decorators import login_required
from datetime import datetime, timezone
from django.urls import reverse
from django.http import JsonResponse
from .models import Auction, Bid
from .forms import ImageUploadForm

# Main page
def index(request):
    # First get all auctions and resolve them
    auction_list = Auction.objects.all()
    for a in auction_list:
        a.resolve()
    # Get all active auctions, oldest first
    latest_auction_list = auction_list.filter(is_active=True).order_by('date_added')
    template = loader.get_template('auctions/index.html')
    context = {
        'title': "Active auctions",
        'auction_list': latest_auction_list,
    }
    return HttpResponse(template.render(context, request))

def auctions(request):
    # Get all auctions, newest first
    auction_list = Auction.objects.order_by('-date_added')
    for a in auction_list:
        a.resolve()
    template = loader.get_template('auctions/index.html')
    context = {
        'title': "All auctions",
        'auction_list': auction_list,
    }
    return HttpResponse(template.render(context, request))

# Details on some auction
def detail(request, auction_id):
    auction = get_object_or_404(Auction, pk=auction_id)
    auction.resolve()
    already_bid = False
    if request.user.is_authenticated:
        if auction.author == request.user:
            own_auction = True
            return render(request, 'auctions/detail.html', {'auction': auction, 'own_auction': own_auction})

        user_bid = Bid.objects.filter(bidder=request.user).filter(auction=auction).first()
        if user_bid:
            already_bid = True
            bid_amount = user_bid.amount
            return render(request, 'auctions/detail.html', {'auction': auction, 'already_bid': already_bid, 'bid_amount': bid_amount})

    return render(request, 'auctions/detail.html', {'auction': auction, 'already_bid': already_bid})
    # try:
    #     auction = Auction.objects.get(pk=auction_id)
    # except Auction.DoesNotExist:
    #     raise Http404("Auction does not exist")
    # return render(request, 'auctions/detail.html', {'auction': auction})

# def results(request, auction_id):
#     response = "You're looking at the results of auction %s."
#     return HttpResponse(response % auction_id)

# Bid on some auction
@login_required
def bid(request, auction_id):
    auction = get_object_or_404(Auction, pk=auction_id)
    auction.resolve()
    bid = Bid.objects.filter(bidder=request.user).filter(auction=auction).first()

    if not auction.is_active:
        return render(request, 'auctions/detail.html', {
            'auction': auction,
            'error_message': "The auction has expired.",
        })

    try:
        bid_amount = request.POST['amount']
        # Prevent user from entering an empty or invalid bid
        if not bid_amount or int(bid_amount) < auction.min_value:
            raise(KeyError)
        if not bid:
            # Create new Bid object if it does not exist
            bid = Bid()
            bid.auction = auction
            bid.bidder = request.user
        bid.amount = bid_amount
        if(auction.min_value<int(bid_amount)):
            auction.min_value = bid_amount
        bid.date = datetime.now(timezone.utc)
    except (KeyError):
        # Redisplay the auction details.
        return render(request, 'auctions/detail.html', {
            'auction': auction,
            'error_message': "Invalid bid amount.",
        })
    else:
        bid.save()
        auction.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        # return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))
        return HttpResponseRedirect(reverse('my_bids', args=()))

        # TODO redirect to my bids
        # template = loader.get_template('auctions/my_bids.html')
        # context = {
        #     'my_bids_list': my_bids_list,
        # }
        # return HttpResponse(template.render(context, request))

        # return HttpResponse(f"You just bid {bid_amount} on auction {auction_id}.")

# Create auction
@login_required
def create(request):
    submit_button = request.POST.get('submit_button')
    if submit_button:
        try:
            title = request.POST['title']
            min_value = request.POST['min_value']
            duration = request.POST['duration']
            # image_uploaded = request.POST['image']
            if not title or not min_value or not duration:
                raise(KeyError)
        except (KeyError):
            # Redisplay the create auction page with an error message.
            return render(request, 'auctions/create.html', {
                'error_message': "Please fill the required fields.",
            })
        else:
            # Create new Bid object
            auction = Auction()
            auction.author = request.user
            auction.title = title
            auction.min_value = min_value
            auction.desc = request.POST['description']
            form = ImageUploadForm(request.POST, request.FILES)
            if form.is_valid():
                image = form.cleaned_data['image']
                auction.image = image
            # auction.date_added = datetime.utcnow()
            auction.date_added = datetime.now(timezone.utc)
            auction.duration = duration
            auction.save()
            # return HttpResponseRedirect(reverse('auctions:detail', args=(auction.id,)))
            return HttpResponseRedirect(reverse('my_auctions', args=()))
    else:
        return render(request, 'auctions/create.html')


@login_required
def my_auctions(request):
    # Get all auctions by user, sorted by date
    my_auctions_list = Auction.objects.all().filter(author=request.user).order_by('-date_added')
    for a in my_auctions_list:
        a.resolve()
    template = loader.get_template('auctions/my_auctions.html')
    context = {
        'my_auctions_list': my_auctions_list,
    }
    return HttpResponse(template.render(context, request))

@login_required
def my_bids(request):
    # Get all bids by user, sorted by date
    my_bids_list = Bid.objects.all().filter(bidder=request.user).order_by('-date')
    for b in my_bids_list:
        b.auction.resolve()

    template = loader.get_template('auctions/my_bids.html')
    context = {
        'my_bids_list': my_bids_list,
    }
    return HttpResponse(template.render(context, request))

def about(request):
    return render(request, 'auctions/about.html')

def success(request):
    return render(request , 'auctions/successPage.html')

def search(request):
    searchListing = Auction.objects.filter(desc__icontains=request.POST["search_keyword"]) | Auction.objects.filter(title__icontains=request.POST["search_keyword"]) 
    print('\n\nsyapa\n\n')
    # result = [
    #     {
    #         "author": str(data.author),
    #         "title": data.title,
    #         "desc": data.desc,
    #         "min_value": str(data.min_value),
    #         # "imageUrl": str(data.imageUrl),
    #         "date_added": data.date_added,
    #         "duration": data.duration,
    #         "is_active": data.is_active,
    #         "final_value": str(data.final_value),
    #     }
    #     for data in searchListing
    # ]
    for a in searchListing:
        a.resolve()
    template = loader.get_template('auctions/search.html')
    context = {
        'searchListing': searchListing,
    }
    print('syapa search')
    return HttpResponse(template.render(context, request))

    # return JsonResponse({
    #     "objects": result
    # })

auctions/templates/auctions/about.html
{% extends "base.html" %}
{% block content %}
<html>
    <title>About Us</title>
    <body>
        <div class="wrapper">
            <a class="auction-card">
                <div><img class="auction_image_index" src="/static/Anish.png"></div>
                <div class="auction-card-title">Anish Pandita</div>
                <li>panditaa@uci.edu</li>
                <li>90688024</li>
                <!-- <a href="#">
                    LinkedIn
                </a> -->
            </a>
            <a class="auction-card">
                <div><img class="auction_image_index" src="/static/GK.jpg"></div>
                <div class="auction-card-title">Gurkanwal Singh Kang</div>
                <li>gurkanwk@uci.edu</li>
                <li>93887116</li>
                <!-- <li><a href="https://www.linkedin.com/in/mayank-chandak/">
                    LinkedIn
                </a></li> -->
            </a>
            <a class="auction-card">
                <div><img class="auction_image_index" src="/static/Mayank.png"></div>
                <div class="auction-card-title">Mayank Chandak</div>
                <li>mchandak@uci.edu</li>
                <li>86041404</li>
                <!-- <a href="https://www.linkedin.com/in/mayank-chandak/">
                    LinkedIn
                </a> -->
            </a>
            <a class="auction-card">
                <div><img class="auction_image_index" src="/static/Neelendu.png"></div>
                <div class="auction-card-title">Neelendu Wadhwa</div>
                <li>neelendw@uci.edu</li>
                <li>92966132</li>
                <!-- <a href="https://www.linkedin.com/in/mayank-chandak/">
                    LinkedIn
                </a> -->
            </a>
        </div>
    </body>
</html>
{% endblock %}

auctions/templates/auctions/create.html
{% extends "base.html" %}
{% block content %}

<h1>Create Auction</h1>
<div class="wrapper">
    <form action="{% url 'auctions:create' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {% if error_message %}<p class="error"><strong>{{ error_message }}</strong></p>{% endif %}
        <span>Enter title:</span>
        <span class="required_field" >*</span>
        <br>
        <input class="textbox" type="text" name="title">
        <br>
        <br>
        <span>Enter description:</span>
        <br>
        <input class="description_box" type="text" name="description">
        <br>
        <br>
        <span>Upload picture:</span>
        <br>
        <input class="textbox required_field" type="file" accept="image/*" name="image">
        <br>
        <br>
        <span>Enter minimum value:</span>
        <span class="required_field" >*</span>
        <br>
        <input class="textbox" type="text" name="min_value">
        <br>
        <br>
        <span>Enter time duration:</span>
        <span class="required_field" >*</span>
        <br>
        <input class="textbox" type="text" name="duration">
        <br>
        <br>
        <br>
        <input type="submit" class="btn btn-primary" name="submit_button" value="Create">
    </form>
</div>

  
{% endblock %}

auctions/templates/auctions/detail.html
{% extends "base.html" %}
{% block content %}

{% block title %}<title>{{ auction.title }} - Auction Rush</title>{% endblock %}

<h1> {{ auction.title }} </h1>
<div class="wrapper">
    {% if not own_auction %}
        {% if auction.is_active %}
        <!-- <div class="bid_box"> -->
        <form action="{% url 'auctions:bid' auction.id %}" method="post">
        <!-- <form action="/auctions/{{ auction.id }}/bid/" method="post"> -->
        {% csrf_token %}
        <div class=\"input_label\">
        {% if error_message %}<p class="error" ><strong>{{ error_message }}</strong></p>{% endif %}
        {% if already_bid %}
            <h3> Current bid: {{ bid_amount }} </h3>
        {% endif %}
        <span>Enter amount ($):</span>
        <span class="required_field" >*</span>
        </div>
        <input class="textbox" type="text" class="input_box" name="amount">
        <br>
        <a><input class="submit_button" type="submit" class="submit_button" value="Bid"></a>
        </form>
        <br>
        <!-- </div> -->
        {% endif %}
    {% endif %}
</div>
<div class="wrapper">
    <span class="auction-card">
        <span><img class="auction_image_index" src="{{ auction.image.url }}" style=" 
            max-width: 100%;margin-top: 5%;" onerror="this.onerror=null; this.src='/static/nofound.png'"></span>
            {% if auction.is_active %}
                {% if auction.remaining_minutes < 2 %}
                    <div class="auction-card-urgent">Less than {{ auction.remaining_minutes }} min</div>
                {% else %}
                    <div class="auction-card-active">Less than {{ auction.remaining_minutes }} min</div>
                {% endif %}
            {% else %}
            <div class="auction-card-inactive">Expired</div>
            {% endif %}
            <div class="auction-card-value">${{ auction.min_value }}</div>
        </div>
    </span>
</div>
{% if auction.desc %}
<div class="wrapper">
    <div class="desc_box">
    <div class="desc_box_title">Description</div>
    <hr>
    {{ auction.desc }}
    </div>
</div>
{% endif %}

{% endblock %}

auctions/templates/auctions/index.html
{% extends "base.html" %}
{% block content %}

<h1>{{ title }}</h1>
{% if auction_list %}
    <div class="wrapper">
    {% for auction in auction_list %}
        <a class="auction-card"  href="{% url 'auctions:detail' auction.id %}"> 
            <div class="container-fluid"><img class="auction_image_index" style=" 
                    max-width: 100%;margin-top: 5%;" src="{{ auction.image.url }}" onerror="this.onerror=null; this.src='/static/nofound.png'" alt=""></div>
            
                <!-- <div class="container-fluid"><img class="auction_image_index" style="
                    max-width: 100%;margin-top: 5%;"src="https://natureconservancy-h.assetsadobe.com/is/image/content/dam/tnc/nature/en/photos/tnc_34284690_1640x1025.jpg?crop=0%2C184%2C1640%2C861&wid=1200&hei=630&scl=1.3666666666666667"/></div> -->
            <div class="auction-card-title">{{ auction.title }}</div>
            {% if auction.is_active %}
                {% if auction.remaining_minutes < 2 %}
                    <div class="auction-card-urgent">Less than {{ auction.remaining_minutes }}</div>
                {% else %}
                    <div class="auction-card-active">Less than {{ auction.remaining_minutes }}</div>
                {% endif %}
            {% else %}
            <div class="auction-card-inactive">Expired</div>
            {% endif %}
            <div class="auction-card-value">${{ auction.min_value }}</div>
            
        </a>
        <!-- <li class="auction-card"><a href="{% url 'auctions:detail' auction.id %}">{{ auction.title }}</a></li> -->
    {% endfor %}
    </div>
{% else %}
    <h4>No auctions are available.</h4>
{% endif %}

{% endblock %}

auctions/templates/auctions/my_auctions.html
{% extends "base.html" %}
{% block title %}<title>My Auctions - Auction Rush</title>{% endblock %}
{% block content %}

<h2> My auctions </h2>
{% if my_auctions_list %}
    <ul class="my-auction-list">
    {% for auction in my_auctions_list %}
        <li class="my-auction-li"><a class="my-auction-link" href="{% url 'auctions:detail' auction.id %}">{{ auction.title }}</a>
            <hr>
            <div class="my-auction-date">Added: {{ auction.date_added }}</div>
            {% if auction.is_active %}
                <span class="my-auction-status-active">
                    Pending
                </span>
                <span class="my-auction-value">
                    ${{ auction.min_value }}
                </span>
            {% else %}
                {% if auction.final_value %}
                <span class="my-auction-status-resolved">
                    Final value: {{ auction.final_value }}$
                </span>
                {% else %}
                <span class="my-auction-status-no_winner">
                    No winner
                </span>
                {% endif %}
            {% endif %}
        </li>
    {% endfor %}
    </ul>
{% else %}
    <h4>No auctions are available.</h4>
{% endif %}

{% endblock %}

auctions/templates/auctions/my_bids.html
{% extends "base.html" %}
{% block title %}<title>My Bids - Auction Rush</title>{% endblock %}
{% block content %}

<h2> My bids </h2>
{% if my_bids_list %}
<ul class="my-bid-list">
    {% for bid in my_bids_list %}
        <li class="my-bid-li"><a class="my-bid-link" href="{% url 'auctions:detail' bid.auction.id %}">{{ bid.auction.title }}</a>
            <hr>
            <div class="my-bid-label">
                My last bid: ${{ bid.amount }}
                <!-- <div class="my-bid-date">({{ bid.date }})</div> -->
            </div>
            {% if bid.auction.is_active %}
                <div class="my-bid-status-active">Pending</div>
            {% else %}
                {% if bid.auction.winner and bid.auction.winner == user %}
                <div>Congratulations !! You have won the bid for <b>{{bid.auction.title }}</b></div>
                <br>
                <div>Please complete the payment to proceed further.</div>    
                <br>
                <div>
                    <div class="my-bid-status-won">Won for ${{ bid.amount }}</div>
                    <div id="paypal-button-container"></div>
                    </div>
                    <script>
                        var amt = '{{ bid.amount }}';
                        // Render the PayPal button into #paypal-button-container
                        paypal.Buttons({
                
                            // Set up the transaction
                            createOrder: function(data, actions) {
                                return actions.order.create({
                                    purchase_units: [{
                                        amount: {
                                            value: parseFloat(amt).toFixed(2)
                                        }
                                    }]
                                });
                            },
                
                            // Finalize the transaction
                            onApprove: function(data, actions) {
                                return actions.order.capture().then(function(orderData) {
                                    // Successful capture! For demo purposes:
                                    console.log('Capture result', orderData, JSON.stringify(orderData, null, 2));
                                    var transaction = orderData.purchase_units[0].payments.captures[0];
                                    //alert('Transaction '+ transaction.status + ': ' + transaction.id + '\n\nSee console for all available details');
                                    
                                        window.localStorage.setItem("author" , "{{bid.auction.author.username}}");
                                        window.localStorage.setItem("phone" , "{{bid.auction.author.phone}}");
                                        window.localStorage.setItem("email" , "{{bid.auction.author.email}}");
                                        window.localStorage.setItem("transactionId" , transaction.id);
                                        window.location.href = "/successPage";
                                        
                                    // Replace the above to show a success message within this page, e.g.
                                    // const element = document.getElementById('paypal-button-container');
                                    // element.innerHTML = '';
                                    // element.innerHTML = '<h3>Thank you for your payment!</h3>';
                                    // Or go to another URL:  actions.redirect('thank_you.html');
                                });
                            }
                
                
                        }).render('#paypal-button-container');
                    </script>
                {% else %}
                    <div class="my-bid-status-lost">Lost</div>
                {% endif %}
            {% endif %}
        </li>
    {% endfor %}
</ul>
{% else %}
    <h4>No bids are available.</h4>
{% endif %}

{% endblock %}

auctions/templates/auctions/search.html
{% extends "base.html" %}
{% block content %}
<h1>{{ title }}</h1>


{% if searchListing %}
    <div class="wrapper">
    {% for auction in searchListing %}
        <a class="auction-card" href="{% url 'auctions:detail' auction.id %}">
            <div class="container-fluid"><img class="auction_image_index" style="
                max-width: 100%;margin-top: 5%;" src="{{ auction.image.url }}" onerror="this.onerror=null; this.src='/static/nofound.png'" ></div>
                <!-- <div class="container-fluid"><img class="auction_image_index" style="
                max-width: 100%;margin-top: 5%;"src="https://natureconservancy-h.assetsadobe.com/is/image/content/dam/tnc/nature/en/photos/tnc_34284690_1640x1025.jpg?crop=0%2C184%2C1640%2C861&wid=1200&hei=630&scl=1.3666666666666667"/></div> -->
            <div class="auction-card-title">{{ auction.title }}</div>
            {% if auction.is_active %}
                {% if auction.remaining_minutes < 2 %}
                    <div class="auction-card-urgent">Less than {{ auction.remaining_minutes }}</div>
                {% else %}
                    <div class="auction-card-active">Less than {{ auction.remaining_minutes }}</div>
                {% endif %}
            {% else %}
            <div class="auction-card-inactive">Expired</div>
            {% endif %}
            <div class="auction-card-value">${{ auction.min_value }}</div>
        </a>
        <!-- <li class="auction-card"><a href="{% url 'auctions:detail' auction.id %}">{{ auction.title }}</a></li> -->
    {% endfor %}
    </div>
{% else %}
    <h4>No auctions are available.</h4>
{% endif %}

{% endblock %}

auctions/templates/auctions/successPage.html
<p id="author">
    
</p>
<script>
    var author_name = window.localStorage.getItem("author");
    document.getElementById("author").innerHTML = author_name;
</script>