auctionrush/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views
from auctions import views as auctions_views

urlpatterns = [
    path('', auctions_views.index, name="index"),
    path('about/', auctions_views.about, name="about"),
    path('myauctions/', auctions_views.my_auctions, name="my_auctions"),
    path('mybids/', auctions_views.my_bids, name="my_bids"),
    path('auctions/', include('auctions.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path("accounts/register", views.register, name="register"),
    path('admin/', admin.site.urls),
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

auctions/urls.py
from django.urls import path

from . import views
app_name = 'auctions'

urlpatterns = [
    path('create/', views.create, name='create'),
    # path('myauctions/', views.my_auctions, name='my_auctions'),
    # Example: /auctions/
    path('', views.auctions, name='auctions'),
    # Example: /auctions/5/
    path('<int:auction_id>/', views.detail, name='detail'),
    # Example: /auctions/5/results/
    # path('<int:auction_id>/results/', views.results, name='results'),
    # Example: /auctions/5/bid/
    path('<int:auction_id>/bid/', views.bid, name='bid'),
    path("search", views.search, name="search"),
    
]

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  {% block title %}<title>ZotVerse</title>{% endblock %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
  <script src="https://www.paypal.com/sdk/js?client-id=AYexVdfsCv1PhFabgk8Z5TLQUDTk1nZzNxOim-44vefTpZJ0MGLeIfL2Dn6HDqCOpfdy_c2UHhqSX3G2&currency=USD"></script>
  {% load static %}
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <!-- <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous"> -->
  <link rel="stylesheet" href="{% static 'font-awesome-4.7.0/css/font-awesome.css' %}">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@5.15.4/css/fontawesome.min.css" integrity="sha384-zIaWifL2YFF1qaDiAo0JFgsmasocJ/rqu7LKYH8CoBEXqGbb9eO+Xi3s6fQhgFWM" crossorigin="anonymous">
  <link rel="shortcut icon" type="image/png" href="{% static 'favicon.png' %}"/>
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</head>
<body>
      {% block sidebar %}
        <ul class="navbar" style="overflow:visible">
          <li class="auction-rush-button">
            <a class="navbar-link" href="{% url 'about' %}">
                ZotVerse
            </a>
        </li>
          <li class="navbar-item"><a class="navbar-link" href="{% url 'auctions:auctions' %}">All Listings</a></li>
          <li class="navbar-item"><a class="navbar-link" href="{% url 'index' %}"">Active Listing</a></li>
          <li class="navbar-item">
          <div class="input-group">
            <div class="form-outline">
              <form method="post" action="/auctions/search" >
              <input name = "search_keyword" type="search" placeholder="Enter the product name" class="form-control" />
              
              
            </div>
            <button type="submit" class="btn btn-primary">
              <span>Search</span>
            </button>
          </form>
          </div>
          
          <!-- <div style = ""> -->
            <!-- class="form-group mx-sm-3 mb-2" -->
            <!-- <li for="" class="sr-only"></li> -->
            <!-- <form method="post" action="/auctions/search" >
              <input name="search_keyword" type="" class="navbar-link" id="" placeholder="search...."/>
              <button type="submit" class="btn">Submit<i class="fa fa-search"></i></button>
            </form> -->
            
            <!-- </div> -->
          </li>
          {% if user.is_authenticated %}
          <!-- <li class="navbar-item"><a class="navbar-link" href="{% url 'my_auctions' %}">My auctions</a></li>
          <li class="navbar-item"><a class="navbar-link" href="{% url 'my_bids' %}">My bids</a></li> -->
          <li class="create-auction-button"><a class="navbar-link" href="{% url 'auctions:create' %}">Create an auction</a> </li>
          {% endif %}   
          {% if user.is_authenticated %}
            <!-- <li class="navbar-item-right"><a class="navbar-link" href="{% url 'logout' %}?next={% url 'index' %}">Logout</a></li> -->
            <!-- <li class="navbar-item-right"><span class="navbar-text">Logged in as: <span class="username">{{ user.get_username }}</span></span></li> -->
            <div class="dropdown mr-5" style="z-index:100 !important">
              <button class="btn btn-primary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Current User: <span class="">{{ user.get_username }}</span>
              </button>
              <div class="dropdown-menu" style="z-index:100 !important" aria-labelledby="dropdownMenuButton">
                <a class="dropdown-item" style="z-index:100 !important" href="{% url 'my_auctions' %}">My auctions</a>
                <a class="dropdown-item" style="z-index:100 !important" href="{% url 'my_bids' %}">My bids</a>
                <a class="dropdown-item" style="z-index:100 !important" href="{% url 'logout' %}?next={% url 'index' %}">Logout</a>
              </div>
            </div>
            {% else %}
            <li class="navbar-item-right"><a class="navbar-link" href="{% url 'login' %}?next={% url 'index' %}">Login</a></li>
            <li class="navbar-item-right"><a class="navbar-link" href="{% url 'register' %}?next={{request.path}}">Register</a></li>
          {% endif %}
          
        </ul>
     {% endblock %}
      <div class="main-content">{% block content %}{% endblock %}</div>
</body>
</html>

templates/base_generic.html
<!DOCTYPE html>
<html lang="en">
<head>
  {% block title %}<title>Flying Dutchman</title>{% endblock %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
  <!-- TODO Add additional CSS in static file -->
  {% load static %}
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">
  <!-- {% load static %} -->
  <!-- <link rel="stylesheet" type="text/css" href="{% static 'auctions/style.css' %}"> -->
</head>
<body>
  <div class="container-fluid">
    <div class="row">
      <div class="col-sm-2">
      {% block sidebar %}
        <ul class="sidebar-nav">
          <li><a href="{% url 'auctions:index' %}">Home</a></li>
          <li><a href="{% url 'my_auctions' %}">My auctions</a></li>
          <li><a href="{% url 'my_bids' %}">My bids</a></li>
          {% if user.is_authenticated %}
            <li>User: {{ user.get_username }}</li>
            <li><a href="{% url 'logout'%}?next={{request.path}}">Logout</a></li>
          {% else %}
            <li><a href="{% url 'login'%}?next={{request.path}}">Login</a></li>
          {% endif %} 
          </ul>
        </ul>
     {% endblock %}
      </div>
      <div class="col-sm-10 ">{% block content %}{% endblock %}</div>
    </div>
  </div>
</body>
</html>

templates/successPage.html
{% extends 'base.html' %}

{% block content %}
<div class="card container-fluid" style = "margin: 10%; width : 80%">
<p>Your transaction was successful. Kindly contact the seller for further steps about delivery through the details below : </p>
<p id="author">
</p>
</div>
<script>
    var author_name = window.localStorage.getItem("author");
    var author_email = window.localStorage.getItem("email");
    var author_phone = window.localStorage.getItem("phone");
    var transaction_ID = window.localStorage.getItem("transactionId");


    
    document.getElementById("author").innerHTML = "<p> Transaction ID : " + transaction_ID +"</p><p>Seller Name : "  + author_name + "</p> <p> Seller Email : " +
         author_email + "<p> Seller Phone No. :" + author_phone ;
</script>
    <img src="/static/thanks.jpeg" style= "vertical-align: middle; height: 250px; width: 50%; margin-left: 25%;">

<!-- <b style = "margin-left: 35%;">Thank you for using ZotVerse, ZOT ZOT ZOT!!</b> -->
{% endblock %}